Spanish, german and some fixes to classes and template
League-of-Foundry-Developers/compendium-browser pull request #3
Opened 2021-02-13 14:57 UTC by JJBocanegra

2021-09-04 21:57 UTC, spetzel2020 requested changes
Other than the references to CMPBrowser.fighter etc, I only formatting changes; am I missing anything.

2021-09-04 21:57 UTC, spetzel2020 commented on lang/en.json
> +}
You've added references to CMPBrowser.rogue, .fighter, .monk without defining them in any of the provided language files.

2021-09-05 00:07 UTC, spetzel2020 commented
Alternatively I can make the fixes and do a manual merge; let me know.

2021-09-05 03:15 UTC, spetzel2020 commented
I've gone through this in more detail and think it will be a lot of work for you to re-pull this against the current version. Instead I will cherry-pick the PR and credit you appropriately in the release v0.6. Thanks!

2021-09-05 03:32 UTC, spetzel2020 commented
Cherry-picked into commit 9d72f1bdac620ca8d03da42e70238653dedd6b5b

2021-09-05 03:32 UTC, closed without merging

2021-09-20 09:27 UTC, JJBocanegra commented
Sorry I just noticed these messages @spetzel2020! Thanks for your hard work!